// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsgmjcbbvecvjoznfjrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZ21qY2JidmVjdmpvem5manJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODMxNTgsImV4cCI6MjA2ODA1OTE1OH0.nxd060sI3wVtRvib5FlGaf1-weteAmCSvBeiV8jdB00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});